
[build]
  node_bundler = "esbuild"
  functions = "backend/functions"
  publish = "frontend/build"
  included_files = [
    "backend/models/**",
    "backend/middlewares/**",
    "backend/routes/**",
    "backend/lib/**",
    "backend/utils/**",
    "backend/helpers/**",
  ]
  command = "npm install && npm run build"

[dev]
  node_bundler = "esbuild"
  functions = "backend/functions"
  publish = "dist"
  included_files = [
    "backend/models/**",
    "backend/middlewares/**",
    "backend/routes/**",
    "backend/lib/**",
    "backend/utils/**",
    "backend/helpers/**",
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
